# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_check_update = false

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "172.17.177.2"
    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "172.17.177.3"
    client.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "1024"
    end
    
    client.vm.provision "shell", path: "setup_ssh.sh"
  end

end