apiVersion: v1
kind: ConfigMap

metadata:
  name: wordpress-config
  namespace: {{ .Values.namespace }}

data:
  MYSQL_DATABASE: "{{ .Values.mysql.database  }}"
  MYSQL_USER: "{{ .Values.mysql.user  }}"
  WORDPRESS_DB_HOST: "{{ .Values.mysql.service.name  }}"
  WORDPRESS_DB_NAME: "{{ .Values.mysql.database  }}"
  WORDPRESS_DB_USER: "{{ .Values.mysql.user  }}"
