apiVersion: v1
kind: Pod

metadata:
  name: my-instrumental-pod
  namespace: dev

spec:
  serviceAccountName: my-service-account

  restartPolicy: Never

  containers:
  - name: kubectl
    image: bitnami/kubectl:latest

    command:
      - /bin/sh
      - -c
      - |
        kubectl get pods -n dev
        sleep 3600
