apiVersion: v1
kind: Secret

metadata:
  name: wordpress-secret
  namespace: {{ .Values.namespace  }}

type: Opaque

stringData:
  MYSQL_PASSWORD: "{{ .Values.mysql.password  }}"
  MYSQL_ROOT_PASSWORD: "{{ .Values.mysql.rootPassword  }}"
  WORDPRESS_DB_PASSWORD: "{{ .Values.mysql.password  }}"
