apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.wordpress.service.name  }}
  namespace: {{ .Values.namespace  }}

spec:
  type: {{ .Values.wordpress.service.type  }}
  selector:
    app: wordpress
  ports:
    - port: {{ .Values.wordpress.service.port  }}
      targetPort: {{ .Values.wordpress.service.port  }}
      nodePort: {{ .Values.wordpress.service.nodePort  }}
