apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: wordpress-pvc
  namespace: dev

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  volumeName: wordpress-pv
  resources:
    requests:
      storage: 2Gi
